services:
  backend:
    container_name: 'tickitzapi'
    # image buatan
    image: roisfaozi/tickitz-api:1
    ports:
      - '8001:8001'
    # .env akan ditimpa dengan envirotment dibawah
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PGHOST=host.docker.internal
      - PGUSER=rois
      - PGPASSWORD=rois
      - PGDATABASE=tickitzz
      - PGPORT=5432
      - JWT_SECRET="alkgjalfijhasdkgjhafkghasdlghak"
    networks:
      - golang

networks:
  golang:
    name: 'golang'
    driver: bridge
    # eksternal true menandakan bahwa network sudah ada, tidak perlu buat lagi
    external: true
# docker compose up -d
# docker compose down
