services:
  backend:
    container_name: 'tickitzapi'
    # image buatan
    image: roisfaozi/tickitz-api:1
    ports:
      - '8001:8001'
    # .env akan ditimpa dengan envirotment dibawah
    environment:
      - DBHOST=rois
      - PGUSER=postgres
      - PGPASSWORD=rois
      - PGDATABASE=tickitzz
    networks:
      - golang

networks:
  gonet:
    name: 'golang'
    driver: bridge
    # eksternal true menandakan bahwa network sudah ada, tidak perlu buat lagi
    external: true
# docker compose up -d
# docker compose down
